version: '3.1'
services:
   mongo:
      image: mongo
      restart: always
      environment:
         MONGO_INITDB_ROOT_USERNAME: cytech
         MONGO_INITDB_ROOT_PASSWORD: Cytech
      ports:
         - 27017:27017
      volumes:
         - db:/data/db
volumes:
   db:
